spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    url: jdbc:sqlserver://localhost;databaseName=SMS
    password: Chinu1994@
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
stock:
  transportType: air
  slaDays: 2    
